//This file is generated by VisualGDB and is used to get accurate IntelliSense
#pragma once
#include <Arduino.h>

#define SYSPROGS_ARDUINO_EXPAND_GENERATED_PROTOTYPES \
	void setup(); \
	float convertToWeight(int32_t i32data); \
	float convertToMilliV(int32_t i32data); \
	void loop(); \

